import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import { Kanit } from "next/font/google";
import Footer from "@/components/Footer";

const kanit = Kanit({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={kanit.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
